;
; File generated by cc65 v 2.13.3
;
	.fopt		compiler,"cc65 v 2.13.3"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_rb_enable
	.import		_rb_set_window
	.import		_rb_map_device
	.export		_main

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp2
	ldx     #$03
	lda     #$00
	jsr     _rb_set_window
	lda     #$01
	jsr     _rb_map_device
	jsr     _rb_enable
	ldx     #$03
	lda     #$00
	ldy     #$00
	jsr     staxysp
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$02
	ldy     #$03
	jsr     staspidx
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$58
	ldy     #$10
	jsr     staspidx
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$D9
	ldy     #$11
	jsr     staspidx
	jsr     incsp2
	rts

.endproc

